devices:
  r1:
    host: 127.0.0.1
    port: 2201
    username: root
    password: frrlab123
    role: router
  r2:
    host: 127.0.0.1
    port: 2202
    username: root
    password: frrlab123
    role: router
  r3:
    host: 127.0.0.1
    port: 2203
    username: root
    password: frrlab123
    role: router
